version: '3.7'
services:
  frontend:
    container_name: desafiolatam-container
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - "4200:4200"
    volumes:
     - ./:/usr/src/app  
    command: bash
